### ISSUE TITLE
Restricted to landfill tiles?

### ISSUE THREAD

**Issue by verso-patrick** [un-smurf/waterfill#3]
I'm trying to understand how waterfill works in the new 2.0 context. Previously, I could add water anywhere on a planet that supported water. Is it only allowed on a water tile has been landfilled? Thanks!

**Comment by un-smurf** [comment]
Hi, in the base 2.0 game (no spage age dlc) then it should work the same as it always has, can place on any tile that isnt already water.
In Space Age i have restricted it to only Navis and Glebe where water is actually available.

If its not working like that for you can you confirm if base game or space age dlc is used

**Comment by verso-patrick** [comment]
Here are the mods im running: 
![image](https://github.com/user-attachments/assets/312967b5-a7ec-4435-b3af-a89500141316)

Attempting to place a waterfill tile does nothing. It highlights the ground, but wont place it. I'm currently on nauvis:
![image](https://github.com/user-attachments/assets/e85f0fa4-9b39-4b63-861d-ffa5dd3124ee)

**Comment by un-smurf** [comment]
ok, looks like i might of missed a surface. i'll have a look thru and hopefully fix asap, can you try placing down in a different area on navis

**Comment by verso-patrick** [comment]
I tried a bunch of different tiles with the same result, could it be incompatible with Alien Biomes?

**Comment by un-smurf** [comment]
it might be that as for space age i have to list the surfaces its allowed on otherwise you can place it everywhere which is way to cheaty. i will try and add Alien Biomes support

**Comment by verso-patrick** [comment]
This surface may be specific to alien biomes now that I'm looking deeper: 
![image](https://github.com/user-attachments/assets/ac2ccdee-cf5f-454c-89a3-1ce584b52c70)

**Comment by un-smurf** [comment]
had a quick look and it should be easy to handle, give me 30-60mins and hopefully i will have an update ready

**Comment by un-smurf** [comment]
ok not as simple as i thought, it doesn't seem to like me using the alien biomes tile names so its gonna take a bit more debuging to find the correct names to use. 
in the mean time if you wanna a quick work around you can edit data.lua and remove
`if mods["space-age"] then
	require("prototypes.item-space")
	require("prototypes.recipe-space")
	
end`

This should then allow it to be placed anywhere on any planet

**Comment by verso-patrick** [comment]
No worries / rush! I know these things take time to adjust to with such a significant update. 

Earendel is the author - it appears to be closed source, but he may be able to provide some insight, etc. in his Discord: https://discord.gg/GDvxHgXjkk

**Comment by un-smurf** [comment]
ok got it working and new version has been pushed to the mod portal

**Comment by verso-patrick** [comment]
Nailed it! Thank you so much - appreciate you and this mod
![image](https://github.com/user-attachments/assets/42e0ebaf-5590-461e-a22a-1fcdc8e5f144)
