### ISSUE TITLE
Change from v1 functionality -- no longer can place on occupied tiles

### ISSUE THREAD

**Issue by Scottin3d** [un-smurf/waterfill#4]
In version 1.x of the game, water tiles were placable on occupied tiles, ie tiles with trees, rocks, etc..  In version 2.x, you are no longer able to place water on occupied tiles.

![image](https://github.com/user-attachments/assets/4dba6bec-ca97-40ae-9e91-e4c99c6e1d3a)

**Comment by un-smurf** [comment]
the api has changed alot in v2.x and i havent found a work around for it yet

**Comment by Scottin3d** [comment]
Ah, no worries.  Appreciate your work

**Comment by un-smurf** [comment]
ok the new version now has 2 mod settings: 
- allow you to disable colliding with items (beware you can kill yourself and builds)  
- allow placement over the top of tree stumps
